package com.example.huy.design;

public class savedata {
    private String edtHoatTaiTieuChuan;
//    private String edtTenDuAn;
    private String edtChieuDaiNhip;
    private String edtChieuDaiNhipTinhToan;
    private String edtBeRongPhanXeChay;
    private String edtBeRongLanCan;
    private String edtTongBeRongToanCuaCau;
    private String edtLoaiLienKetSuDung;
    private String edtCauTaoDamChu;
    private String edtMatCatNgangDamChu;
    private String edtCuongDoChiuNenCuaBeTong;
    private String edtTiTrongCuaBeTong;
    private String edtModuynDanHoiCuaBeTong;
    private String edtChieuDayBMC;
    private String edtChieuDayLopPhu;
    private String edtTytrongVLlamLopPhu;
    private String edtThepKetCau;
    private String edtModuynDanHoiThep;
    private String edtCuongDoChiuKeoMIN;
    private String edtCuongDoChayMIN;
    private String edtTiTrongThep;
    private String edtSoLuongDamChu;
    private String edtKhoangCachGiuaDC;
    private String edtChieuDaiPhanHang;
    private String edtChieuCaoDC;
    private String edtChieuRongBanCanhTren;
    private String edtChieuDayBCT;
    private String  edtChieuRongBCD;
    private String edtChieuDayBCD;
    private String edtChieuDaySuonDam;
    private String edtChieuCaoSuon;
    private String edtSoLuongDamNgang1Nhip;
    private String edtTongSoDamNgang;
    private String  edtYv;
    private String edtKhoangCachTimDNĐenauDC;
    private String edtS2;
    private String edthn;
    private String edtbn;
    private String edttfdn;
    private String edttwdn;
    private String edthwdn;
    private String edta;
    private String edtnlkn;
    private String  edthlkn;
    private String edtSlkn;
    private String edtb;
    private String edtAtg;
    private String edtDCneo;
    private String edtDClcT;
    private String edtDClcBT;
    private String edtPL;
    private String edtT;
    private String  edtDtt;
    private String edtDtt_ct;
    private String edtDbaove_t;
    private String  edtd0;
    private String edtnn;
    private String edtdneo;
    private String edtpn;

}
